# Auto-generated by bin/compile-test-deps — do not edit by hand.
# Per-method runtime dependencies traced by Rotoscope.
# Each entry becomes a Nix derivation; deps are the precise set of
# files whose code executed during that test method.

[
  {
    name = "MCPM--Commands--InstallTest-test_invoke_installs_missing_mods";
    testFile = "test/mcpm/commands/install_test.rb";
    methodName = "test_invoke_installs_missing_mods";
    deps = [
      "lib/mcpm/commands/install.rb"
      "lib/mods/mods.rb"
      "test/mcpm/commands/install_test.rb"
      "test/test_helper.rb"
    ];
    bootDeps = [
      "lib/mcpm/commands/install.rb"
      "lib/mods/downloader.rb"
      "lib/mods/minecraft_version.rb"
      "lib/mods/modrinth.rb"
      "lib/mods/mods.rb"
      "lib/mods/updater.rb"
      "lib/utility/yaml.rb"
      "test/test_helper.rb"
    ];
  }
  {
    name = "MCPM--Commands--OutdatedTest-test_check_mod_versions";
    testFile = "test/mcpm/commands/outdated_test.rb";
    methodName = "test_check_mod_versions";
    deps = [
      "lib/mcpm/commands/outdated.rb"
      "lib/mods/mods.rb"
      "test/mcpm/commands/outdated_test.rb"
      "test/test_helper.rb"
    ];
    bootDeps = [
      "lib/mcpm/commands/outdated.rb"
      "lib/mods/downloader.rb"
      "lib/mods/minecraft_version.rb"
      "lib/mods/modrinth.rb"
      "lib/mods/mods.rb"
      "lib/mods/updater.rb"
      "lib/utility/yaml.rb"
      "test/test_helper.rb"
    ];
  }
  {
    name = "MCPM--Commands--OutdatedTest-test_invoke";
    testFile = "test/mcpm/commands/outdated_test.rb";
    methodName = "test_invoke";
    deps = [
      "lib/mcpm/commands/outdated.rb"
      "lib/mods/mods.rb"
      "test/mcpm/commands/outdated_test.rb"
      "test/test_helper.rb"
    ];
    bootDeps = [
      "lib/mcpm/commands/outdated.rb"
      "lib/mods/downloader.rb"
      "lib/mods/minecraft_version.rb"
      "lib/mods/modrinth.rb"
      "lib/mods/mods.rb"
      "lib/mods/updater.rb"
      "lib/utility/yaml.rb"
      "test/test_helper.rb"
    ];
  }
  {
    name = "MCPM--Commands--UpgradeTest-test_invoke";
    testFile = "test/mcpm/commands/upgrade_test.rb";
    methodName = "test_invoke";
    deps = [
      "lib/mcpm/commands/upgrade.rb"
      "lib/mods/minecraft_version.rb"
      "lib/mods/mods.rb"
      "test/mcpm/commands/upgrade_test.rb"
      "test/test_helper.rb"
    ];
    bootDeps = [
      "lib/mcpm/commands/upgrade.rb"
      "lib/mods/downloader.rb"
      "lib/mods/minecraft_version.rb"
      "lib/mods/modrinth.rb"
      "lib/mods/mods.rb"
      "lib/mods/updater.rb"
      "lib/utility/yaml.rb"
      "test/test_helper.rb"
    ];
  }
  {
    name = "MCPM--ExampleTest-test_example";
    testFile = "test/example_test.rb";
    methodName = "test_example";
    deps = [
      "test/example_test.rb"
    ];
    bootDeps = [
      "lib/mods/minecraft_version.rb"
      "lib/mods/modrinth.rb"
      "test/test_helper.rb"
    ];
  }
  {
    name = "ModConfigCacheTest-test_apply_updates_invalidates_the_cached_jar_list_after_replacing_the_mods_directory";
    testFile = "test/mod_config_cache_test.rb";
    methodName = "test_apply_updates_invalidates_the_cached_jar_list_after_replacing_the_mods_directory";
    deps = [
      "lib/mods/mods.rb"
      "lib/mods/updater.rb"
      "test/mod_config_cache_test.rb"
    ];
    bootDeps = [
      "lib/mods/downloader.rb"
      "lib/mods/minecraft_version.rb"
      "lib/mods/modrinth.rb"
      "lib/mods/mods.rb"
      "lib/mods/updater.rb"
      "lib/utility/yaml.rb"
      "test/test_helper.rb"
    ];
  }
  {
    name = "ModConfigCacheTest-test_install_mod_invalidates_the_cached_jar_list";
    testFile = "test/mod_config_cache_test.rb";
    methodName = "test_install_mod_invalidates_the_cached_jar_list";
    deps = [
      "lib/mods/mods.rb"
      "test/mod_config_cache_test.rb"
    ];
    bootDeps = [
      "lib/mods/downloader.rb"
      "lib/mods/minecraft_version.rb"
      "lib/mods/modrinth.rb"
      "lib/mods/mods.rb"
      "lib/mods/updater.rb"
      "lib/utility/yaml.rb"
      "test/test_helper.rb"
    ];
  }
  {
    name = "ModConfigCacheTest-test_update_mod_invalidates_the_cached_jar_list_after_removing_the_old_jar";
    testFile = "test/mod_config_cache_test.rb";
    methodName = "test_update_mod_invalidates_the_cached_jar_list_after_removing_the_old_jar";
    deps = [
      "lib/mods/mods.rb"
      "test/mod_config_cache_test.rb"
    ];
    bootDeps = [
      "lib/mods/downloader.rb"
      "lib/mods/minecraft_version.rb"
      "lib/mods/modrinth.rb"
      "lib/mods/mods.rb"
      "lib/mods/updater.rb"
      "lib/utility/yaml.rb"
      "test/test_helper.rb"
    ];
  }
]
