# Auto-generated by bin/compile-test-deps — do not edit by hand.
#
# Tier 1 (shared) deps from test_helper.rb are handled separately
# in flake.nix. The srcs listed here are the per-test delta.
#
# Shared deps (tier 1): lib/mods/minecraft_version.rb, lib/mods/modrinth.rb, test/test_helper.rb

{
  _shared = {
    srcs = [
      "lib/mods/minecraft_version.rb"
      "lib/mods/modrinth.rb"
      "test/test_helper.rb"
    ];
  };

  "test/example_test.rb" = {
    srcs = [
    ];
  };

  "test/mcpm/commands/install_test.rb" = {
    srcs = [
      "lib/mcpm/commands/install.rb"
      "lib/mods/downloader.rb"
      "lib/mods/mods.rb"
      "lib/mods/updater.rb"
      "lib/utility/yaml.rb"
    ];
  };

  "test/mcpm/commands/outdated_test.rb" = {
    srcs = [
      "lib/mcpm/commands/outdated.rb"
      "lib/mods/downloader.rb"
      "lib/mods/mods.rb"
      "lib/mods/updater.rb"
      "lib/utility/yaml.rb"
    ];
  };

  "test/mcpm/commands/upgrade_test.rb" = {
    srcs = [
      "lib/mcpm/commands/upgrade.rb"
      "lib/mods/downloader.rb"
      "lib/mods/mods.rb"
      "lib/mods/updater.rb"
      "lib/utility/yaml.rb"
    ];
  };

  "test/mod_config_cache_test.rb" = {
    srcs = [
      "lib/mods/downloader.rb"
      "lib/mods/mods.rb"
      "lib/mods/updater.rb"
      "lib/utility/yaml.rb"
    ];
  };

}
